wiki_dir_path: '/opt/wiki'
wiki_deploy_key: 'wiki_deploy_key'
wiki_repo: 'git@github.com:artis3n/personal-wiki.git'

gollum_gems:
  - gollum

gollum_yum_remove_dependencies:
  - cmake

yum_dependencies:
  - curl
  - gpg
  - procps
  - make
  - tar
  - git
  - cronie

cmake_version: '3.19'
ruby_version: '3.0.0'

prepare_yum_packages:
  - python3
  - python3-pip
  - python3-wheel
  - python3-setuptools
  - coreutils
  - shadow-utils
  - yum-utils
