wiki_repo: 'git@github.com:artis3n/personal-wiki.git'
wiki_domain: 'wiki.artis3nal.com'

wiki_dir_path: '/opt/wiki'
wiki_deploy_key: 'wiki_deploy_key'
wiki_git_config:
  - { name: 'name', value: 'Gollum Wiki' }

cmake_version: '3.19'
ruby_version: '2.7.2'

gollum_gems:
  - gollum

gollum_yum_remove_dependencies:
  - cmake

yum_dependencies:
  - curl
  - gpg
  - procps
  - make
  - tar
  - git
  - cronie

certbot_yum_dependencies:
  - nginx
  - certbot
  - python2-certbot-nginx

prepare_yum_packages:
  - python3
  - python3-pip
  - python3-wheel
  - python3-setuptools
  - coreutils
  - shadow-utils
  - yum-utils
