- name: System | Install Dependencies
  ansible.builtin.yum:
    name: '{{ yum_dependencies }}'
    state: present

- name: System | Copy Tailscale IP Script
  ansible.builtin.copy:
    src: './files/tailscale_ip.sh'
    dest: '/home/ec2-user/tailscale_ip.sh'
    owner: 'ec2-user'
    group: 'ec2-user'
    mode: '0755'
