- name: Prepare
  hosts: all
  become: yes
  gather_facts: false

  vars_files:
    - ../../vars.yml

  tasks:
    - name: Test Nginx Server
      ansible.builtin.command:
        cmd: curl http://127.0.0.1:80/
      register: curl_cmd

    - name: Test
      debug:
        var: curl_cmd
