name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Init
        run: terraform init
        working-directory: terraform

      - name: Format
        run: terraform fmt -check
        working-directory: terraform

      - name: Validate
        run: terraform validate
        working-directory: terraform

      - name: Plan
        run: terraform plan
        working-directory: terraform
